### ISSUE TITLE
Run without building or pulling a Docker container

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#1]
**Is your enhancement request related to a problem? Please describe.**

Building a Docker image for every run wastes time and resources.

Pulling a pre-made image may be more efficient.

Actions runners provide everything we need, though, so we don't need another Docker container at all.

**Describe the solution you'd like**

Users can run this action in their workflows without having to build or pull a Docker image.

**Describe alternatives you've considered**

We can skip building the image if the Action pulls a pre-built image. If your registry requires authentication, though (like GitHub's does), there's no way to provide the user's credentials in a workflow such that they can be used to pull the image.

**Additional context**

I'm having so much fun!

**Comment by solvaholic** [comment]
> Pulling a pre-made image may be more efficient.

Well, it's faster anyway.

> Actions runners provide everything we need, though, so we don't need another Docker container at all.

If we were to install zero dependencies, or fewer of them, this may make more sense. I arbitrarily installed all dependencies in the Docker hub image.

> If your registry requires authentication, though (like GitHub's does), there's no way to provide the user's credentials in a workflow such that they can be used to pull the image.

That's what drove me over to Docker hub. Once I learn how to pull anonymously from a GitHub Docker registry, I'll bring it there.

Closing this for now, may revisit if I find performance advantages or learn to use GitHub's registry for this.

**Comment by pavelpulec** [comment]
Hello,

I know this issue was closed a while ago but still it would be interested to have documented how to run this GitHub Action on a custom image with all requirements.

I tried that but I'm getting this error:

```
/__w/_temp/1b0110a2-cfc6-41b3-bff1-a1222d6a57d7.sh: line 1: /home/runner/work/_actions/solvaholic/octodns-sync/main/scripts/run.sh: No such file or directory
```

It looks like GitHub Actions do some magic with paths and how GitHub Action's code is handled. But I am unable to debug it and find the solution for that.

**Comment by solvaholic** [comment]
Hi @pavelpulec 👋  

> how to run this GitHub Action on a custom image with all requirements.

Currently this Action runs `octodns-sync` from https://github.com/octodns/octodns on an Actions runner, and it expects the user to install required packages as part of their Actions workflow.

If your objective is to have your workflow install all the octodns providers, you could have your workflow install the requirements.txt provided in octodns/octodns-docker:
https://github.com/octodns/octodns-docker/blob/main/all/requirements.txt

However, that will not address the error you mentioned:

> ```
> /__w/_temp/1b0110a2-cfc6-41b3-bff1-a1222d6a57d7.sh: line 1: /home/runner/work/_actions/solvaholic/octodns-sync/main/scripts/run.sh: No such file or directory
> ```

If your objective is to create a custom Docker image to run `octodns-sync`, it will be simpler to avoid this Action and start with the octodns/octodns-docker Dockerfile:
https://github.com/octodns/octodns-docker/blob/main/all/Dockerfile

Please let me know if this info helps, or if it seems like I've misunderstood what you're asking. Thank you! :bow:
