### ISSUE TITLE
Unreleased version notes included in dependabot changelog

### ISSUE THREAD

**Issue by xt0rted** [solvaholic/octodns-sync#64]
Dependabot is including the unreleased section in the changelog notes for `v2.2`. I think it's due to the version number in the title.

I'm not sure why it picked the `v2.2` tag instead of `v2.2.0`, maybe the changelog content is actually a result of that 🤷‍♂️. I tried rerunning dependabot but it says a PR already exists for the most recent version at 7d09147688ae2ad2c725fde59aecadb3ed6b2392 which I guess is because there's a `v2`, `v2.2`, and `v2.2.0` tag for it.

![image](https://user-images.githubusercontent.com/831974/117737548-1a6f2800-b1c8-11eb-9a93-15814204d853.png)

**Comment by solvaholic** [comment]
Yikes! I've been overlooking this issue. Please forgive my delays in responding.

Thank you @xt0rted for bringing this up :bow: It reminds me of #34 .. I'll dig into it this week. At a minimum I can remove the version from the _Unreleased_ section of the changelog.

I'd like to stop having the shortened tags, but I feel like they're needed for something. Will check into that as well.

**Comment by solvaholic** [comment]
What needs to happen, to solve this issue?

I think I see: a) Ensure the changelog in the release only shows releases, b) Leave the _Unreleased_ section of changelog in `main` without a number on it, and c) Get rid of the vX and vX.Y tags, use only vX.Y.Z.

Would that get it, @xt0rted?

**Comment by xt0rted** [comment]
@solvaholic For `a` & `b` I think that's right, but for `c` I think the only one that needs to be removed is `vX.Y`. The recommended versioning strategy is to have a `vX` and `vX.Y.Z` with `vX` being updated to point to the latest `vX.Y.Z` on each release. There's some debate over this since it's abusing git's default behavior, but it's what the official actions do as well as most 3rd party ones including all of my own.

**Comment by solvaholic** [comment]
👋 I released v2.3.0 just a bit ago and brought the v2 tag - and not a v2.3 tag - with it. If you get an update from Dependabot, @xt0rted, please let me know whether it's more like what you'd expect.

**Comment by xt0rted** [comment]
Looks good to me.

![image](https://user-images.githubusercontent.com/831974/127424487-0097c4e6-d427-404a-9d80-22a788ac8c92.png)

![image](https://user-images.githubusercontent.com/831974/127424527-908389e5-afc0-42ee-b569-eedfc4bd257b.png)

**Comment by solvaholic** [comment]
Sweet! Thank you for calling this out, @xt0rted, and helping me see how to solve it :bow:
