### ISSUE TITLE
`set-output` is being deprecated

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#94]
## Description

The `set-output` method of setting Action outputs is being deprecated. [Use environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files), or something else, instead.

## Context

Docs about the deprecation, and about how to handle it:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

**Comment by solvaholic** [comment]
6a909e6f15ed161ff056f14b9c24a5d1148fdfc9 [failed](https://github.com/solvahol/dns/actions/runs/3276932209/jobs/5393573425) like this:

> <img width="808" alt="image" src="https://user-images.githubusercontent.com/14636658/196547294-4a7e148d-5fbd-4e99-8c60-e2755fc3526b.png">

**Comment by solvaholic** [comment]
d917c7ce6c7eb165c7d4a6f2fae369e72da9fa37 added [a comment](https://github.com/solvahol/dns/pull/41#issuecomment-1283067786), but not the expected one:

> <img width="443" alt="image" src="https://user-images.githubusercontent.com/14636658/196555885-22d7dafa-e9e4-47f4-9ff8-7762d0bf61df.png">

So I think `octodns-sync` succeeded:

https://github.com/solvaholic/octodns-sync/blob/d917c7ce6c7eb165c7d4a6f2fae369e72da9fa37/scripts/run.sh#L24-L30

And I think the **plan** output was set:

https://github.com/solvaholic/octodns-sync/blob/d917c7ce6c7eb165c7d4a6f2fae369e72da9fa37/scripts/run.sh#L40-L42

I think that was exposed in the Validate job [this way](https://github.com/solvahol/dns/blob/14a55c708003131171e443f93c5beee9b6b290dd/.github/workflows/octodns-validate.yml#L74-L75):

```yaml
    outputs:
      plan: ${{ steps.octodns-sync.outputs.plan }}
```

If a) the plan file was written and b) it's available as expected in `${{ steps.octodns-sync.outputs.plan }}` then I think the changes for issue94 won't affect how the output is used in other workflow job steps. How can I validate whether this are both true?

Maybe try reapplying that sequence of replacements that were required before?

**Comment by solvaholic** [comment]
🎉 7a47ad1 got the output:

> <img width="520" alt="image" src="https://user-images.githubusercontent.com/14636658/196577774-c1b14bf2-8ec3-4aed-9d70-dca44b8308ed.png">

It's still not doing what I expect, tho, so I assume I've overlooked something. My test setup in **sovahol/dns** is running out-of-date octodns, so I'll start by updating that.

**Comment by solvaholic** [comment]
Ok, [0f3f924](https://github.com/solvaholic/octodns-sync/commit/0f3f924c960f97954cc3dedb03f589325aa5ee09) gets it right I think. It even updated [the pull request comment](https://github.com/solvahol/dns/pull/41#issuecomment-1283067786) 🎉 

I'll go ahead and merge these changes into **issue92**.

**Comment by barnumbirr** [comment]
@solvaholic any plans on creating a new release to include this change? I'd rather not see the action stop working if Github suddenly disables `set-output`.

**Comment by solvaholic** [comment]
Hi @barnumbirr Thank you for bumping this! :bow:

I think I dropped the ball around here: https://github.com/solvaholic/octodns-sync/pull/96#issuecomment-1290845868

I'll pick it up there and, yes, get this change into a release. Should be able to finish that up this coming weekend, 11-12 Feb.
